# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d6cf45ecc5ed8071a431c7fce2506d42"
name = "strategic-sale-app"
handle = "strategic-sale-app"
application_url = "https://hwy-throughout-notification-registration.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "malik-checkout-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hwy-throughout-notification-registration.trycloudflare.com/auth/callback",
  "https://hwy-throughout-notification-registration.trycloudflare.com/auth/shopify/callback",
  "https://hwy-throughout-notification-registration.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
